name: 'Helm Publish Action'
description: 'Github Action to simplify Helm Chart publish into a Registry'
inputs:
  workingDirectory:
    description: 'Working directory'
    default: '.'
    required: false
  tailscaleKey:
    description: 'Tailscale AuthKey'
    default: ''
    required: false
  repository:
    description: 'URL of your repository'
    required: true
  username:
    description: 'Username to use on your repository'
    required: true
  password:
    description: 'Password to use on your repository'
    required: true
  beforeHook:
    description: 'Command to execute before publishing'
    default: ''
    required: false
runs:
  using: "composite"
  steps:
    - name: Install Helm
      shell: bash
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        helm plugin install https://github.com/chartmuseum/helm-push

    - name: Tailscale
      uses: tailscale/github-action@v1
      if: ${{ github.event.inputs.tailscaleKey !== '' }}
      with:
        authkey: ${{ github.event.inputs.tailscaleKey }}

    - name: Add repository
      shell: bash
      run: |
        helm repo add charts ${{ github.event.inputs.repository }}

    - name: Execute Before Hook
      shell: bash
      if: ${{ github.event.inputs.beforeHook !== '' }}
      working-directory: ${{ github.event.inputs.workingDirectory }}
      run: ${{ github.event.inputs.beforeHook }}

    - name: Update dependencies
      shell: bash
      working-directory: ${{ github.event.inputs.workingDirectory }}
      env:
        HELM_REPO_USERNAME: ${{ secrets.DOCKER_INTERNAL_USERNAME }}
        HELM_REPO_PASSWORD: ${{ secrets.DOCKER_INTERNAL_PASSWORD }}
      run: |
        helm dependencies update

    - name: Lint
      shell: bash
      working-directory: ${{ github.event.inputs.workingDirectory }}
      run: |
        helm lint

    - name: Publish
      shell: bash
      working-directory: ${{ github.event.inputs.workingDirectory }}
      env:
        HELM_REPO_USERNAME: ${{ secrets.DOCKER_INTERNAL_USERNAME }}
        HELM_REPO_PASSWORD: ${{ secrets.DOCKER_INTERNAL_PASSWORD }}
      run: |
        helm cm-push . charts